---
# Common roles
- hosts: private-server
  become: yes
  roles:
  - { role: "fail2ban" }
  - { role: "ufw" }
  - { role: "sshd" }
  - { role: "rclone-hubic" }
  - { role: "telegram-bot" }

- include: "telegram-bot-fail2ban.yml"
- include: "sshd-telegram-bot.yml"

# Static site
- hosts: private-server
  become: yes
  roles:
  - { role: "static-page" }
