---
- hosts: private-server
  gather_facts: no
  roles:
  - { role: "kimsufi",
      kimsufi_service_name: "{{ inventory_hostname }}",
      kimsufi_template: "private-server",
      kimsufi_state: "reinstalled" }
