---
- hosts: private-server
  gather_facts: no
  roles:
  - { role: "kimsufi",
      kimsufi_service_name: "{{ inventory_hostname }}",
      kimsufi_template: "private-server", 
      kimsufi_application_key: "***REMOVED***",
      kimsufi_application_secret: "***REMOVED***",
      kimsufi_consumer_key: "***REMOVED***",
      kimsufi_state: "reinstalled" }
