- hosts: private-server
  become: yes
  tasks:
  - name: add telegram-bot in fail2ban-action
    copy:
      content: |
        #!/bin/bash
        declare action="${1}"
        declare ip="${2}"
        declare cause="${3}"
        case "${action}" in
          "ban")
            telegram-bot send-message --text "IP ${ip} has just been banned because of ${cause}. "
            ;;
          "unban")
            telegram-bot send-message --text "IP ${ip} has just been unbanned. "
            ;;
        esac
      dest: "/etc/fail2ban-action.d/telegram-bot.conf"
      owner: "root"
      mode: "u=rwx,g=rx,o="
